### ISSUE TITLE
[generate:theme:setting] Theme settings default values

### ISSUE THREAD

**Issue by itsdarrylnorris** [hechoendrupal/drupal-console#1641]
## Problem / Motivation

We should add the ability of settings default values on a theme In Drupal 8 

**config/install/THEME.settings.yml**

```
settings:
  features:
      comment_user_picture: true
      comment_user_verification: true
      favicon: true
      logo: true
      name: true
      node_user_picture: true
      slogan: true
```

For more information - https://www.drupal.org/node/2382645
## Solution
- We need to add ability of running a generator that generate this type of code.
- We should also add this functionality to the generate:theme by using the chain.
