### ISSUE TITLE
[console] Add examples to commands

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/drupal-console#2306]
### Problem/Motivation

Increase project adoption by making easy to understand how to use it.
### Solution

Add examples "how to execute" to command translation files

Adding this to gitbook rendering process is already automated

As an example, we have the `config:override` command

Translation file [config.override.yml](https://github.com/hechoendrupal/DrupalConsole/blob/master/config/translations/en/config.override.yml)

Content of this file:

```
description: 'Override config value in active configuration.'
...
examples:
    - description: 'Set the Contact module flood limit to 10.'
      execution: 'drupal config:override contact.settings flood.limit 10'
```

![](https://monosnap.com/file/e5wwpNS1hXMVxlpdPAWUp8cvF0Wwt1.png)
### Generate examples

We can generate those examples by executing each command and pass the `--generate-inline` option.
![](https://monosnap.com/file/6PukxIpCv9odx7fz6y4kTmGzD8Lyhu.png)
