### ISSUE TITLE
[feature] Allow setting a default alias.

### ISSUE THREAD

**Issue by thom8** [hechoendrupal/drupal-console#2340]
It would be useful to set a default alias while working on a particular site.
Similar functionality exists in drush -- https://drushcommands.com/drush-8x/core/site-set/

Basically, once you set the alias all following commands will run against this alias until it is reset.

It would be even better if it could also be exposed to the bash prompt like -- https://github.com/drush-ops/drush/blob/659f67712adab143a2c921f9f23828782e414e8d/examples/example.prompt.sh#L10

so it's easy to see which in the current active alias.

**Comment by jmolivas** [comment]
This is available on latest release 1.0.0-beta-1 by adding this to `~/.console/config.yml`
```
application:
 ...
    default:
        global:
            options:
                target: drupalvm.dev
```
NOTE: Where `drupalvm.dev` is the site alias name you want to set.
