### ISSUE TITLE
[chain] quick-start module:install throws error

### ISSUE THREAD

**Issue by kgaut** [hechoendrupal/drupal-console#2411]
By using the following chained commands, Console throws error : 

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "module:install" is not defined.                        
  Did you mean one of these?                                      
      site:install                                                
      module:update                                               
      module:download         
```

Here's the chained command based on quick-start : 

```
commands:
# Download Drupal
  - command: site:new
    arguments:
      directory: 'drupal8.dev'
    options:
      latest: 'true'
# Install Drupal
  - command: site:install
    options:
      langcode: fr
      db-type: sqlite
      db-file: sites/default/files/.ht.sqlite
      site-name: 'Awesome website'
      site-mail: admin@example.com
      account-name: me
      account-mail: me@email.net
      account-pass: password
    arguments:
      profile: standard
# Install modules
  - command: module:install
    arguments:
      module:
        - ctools
  - command: module:install
    arguments:
      module:
        - big_pipe
        - pathauto
# Rebuild caches
  - command: cache:rebuild
    arguments:
      cache: all
# Start php built-in server
  - command: server
```

On gitter @novia713 said that it works with console 1.0.0-alpha2 but not on last beta (1.0.0-beta2)
