### ISSUE TITLE
[module:install] Not working after install

### ISSUE THREAD

**Issue by Saphyel** [hechoendrupal/drupal-console#2548]
I don't know if this will be fix (if we move to composer it'll be pointless...) but if you have a file like this:

```
commands:
# Install Drupal
  - command: site:install
    options:
      langcode: 'en'
      db-type: 'mysql'
      db-host: '%{{db_host|localhost}}'
      db-name: '%{{db_name|d8}}'
      db-user: 'root'
      db-pass: 'root'
      db-port: '3306'
      site-name: 'Drupal 8 site'
      site-mail: 'admin@example.org'
      account-name: 'admin'
      account-mail: 'admin@example.org'
      account-pass: 'admin'
    arguments:
      profile: '%{{profile|standard}}'
#Enable modules
  - command: module:install
    arguments:
      module:
        - webprofiler
```

You'll see actually this happening:
![screenshot from 2016-07-30 12-12-49](https://cloud.githubusercontent.com/assets/5764721/17270024/57894c94-5650-11e6-8f44-e8eba5cf4fcf.png)
![screenshot from 2016-07-30 12-12-38](https://cloud.githubusercontent.com/assets/5764721/17270026/5d44bede-5650-11e6-9db0-4ff67b6925d2.png)
