### ISSUE TITLE
generate:routesubscriber service malformed

### ISSUE THREAD

**Issue by superbiche** [hechoendrupal/drupal-console#2550]
Hi, and first let me thank you for this great tool.

I've generated my first RouteSubscriber. My module already had a mymodule.services.yml file that was empty (I removed old services but kept the file in case I needed it again).
On cache rebuild, I saw the yaml was malformed: 

>  Array to string conversion in Drupal\Core\DependencyInjection\YamlFileLoader->validate()

So I checked mymodule.services.yml:

```
mymodule.route_subscriber:   
  class: Drupal\mymodule\Routing\RouteSubscriber  
  tags:  
    - { name: event_subscriber }
```

but it should have been: 

```
services:  
  mymodule.route_subscriber:   
    class: Drupal\mymodule\Routing\RouteSubscriber  
    tags:  
      - { name: event_subscriber }
```

I'm not sure whether this problem was caused by the fact mymodule.services.yml already existed.
