### ISSUE TITLE
RequirementChecker errors should be more-specific

### ISSUE THREAD

**Issue by russellvt** [hechoendrupal/drupal-console#2582]
When throwing requirements errors (possibly others?), the drupal script should be much more specific in requirements failures:

> % drupal check
> PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/local/bin/drupal/src/Utils/RequirementChecker.php on line 71
> 
> [ERROR] The extension "curl" is missing.

I'm assuming that should be a PEAR extension, though Google search doesn't yield too much useful information (and this is a fairly stripped host, in terms of "extra" extensions, etc). It would be nice if, in conditions such as this, it could at least be specific enough to say "install php5-curl" (or something similar).

**Comment by jmolivas** [comment]
I just saw and fix this error, fix will be available on next release.

**Comment by jmolivas** [comment]
This is the fixed file, you can update your `~/.console/phpcheck.yml` file
```
requirements:
  php:
    required: 5.5.9
  configurations:
    required:
      - date.timezone: "America/Tijuana"
      - memory_limit: 1024M
    recomended: {}
  extensions:
    required:
      - date
      - dom
      - filter
      - gd
      - hash
      - json
      - pcre
      - pdo
      - session
      - SimpleXML
      - SPL
      - tokenizer
      - xml
      - curl
    recommended: {}
```
