### ISSUE TITLE
Doesn't recognize drupal directory

### ISSUE THREAD

**Issue by kentr** [hechoendrupal/drupal-console#2785]
## Problem / motivation

After updating drupal console globally and installing drupal console within my drupal directory, I'm getting this error on `drupal list`:

```
[WARNING] In order to list all of the available commands, you should run this against a drupal root directory. 
```

The directory is definitely a working drupal 8.1.10 installation.  `drush status` returns:

```
 Drupal version                  :  8.1.10                                             
 Site URI                        :  http://default                                     
 Database driver                 :  mysql                                              
 Database hostname               :  localhost                                          
 Database port                   :  3306                                               
 Database username               :  drupal                                             
 Database name                   :  drupal                                             
 Drupal bootstrap                :  Successful                                         
 Drupal user                     :                                                     
 Default theme                   :  bartik                                             
 Administration theme            :  seven                                              
 PHP executable                  :  /usr/bin/php                                       
 PHP configuration               :  /etc/php/7.0/cli/php.ini                           
 PHP OS                          :  Linux                                              
 Drush script                    :  /usr/local/share/drush/drush.php                   
 Drush version                   :  9.0-dev-ga9ef364                                   
 Drush temp directory            :  /tmp                                               
 Drush configuration             :                                                     
 Drush alias files               :  /home/vagrant/.drush/site.aliases.drushrc.php 
 Install profile                 :  standard                                           
 Drupal root                     :  /var/www/drupalvm                                  
 Drupal Settings File            :  sites/default/settings.php                         
 Site path                       :  sites/default                                      
 File directory path             :  sites/default/files                                
 Temporary file directory path   :  /tmp
```

**Comment by kentr** [comment]
Hmm...  I don't get the error when I run the executable at `vendor/bin/drupal`.

**Comment by s3than** [comment]
`drush status
 Drupal version                  :  8.1.10                                            
 Site URI                        :  http://default                                    
 Database driver                 :  mysql                                             
 Database hostname               :  dpe-mysql                                         
 Database port                   :  3306                                              
 Database username               :  user                                              
 Database name                   :  db                                                
 Drupal bootstrap                :  Successful                                        
 Drupal user                     :                                                    
 Default theme                   :  bartik                                  
 Administration theme            :  seven                                             
 PHP executable                  :  /usr/local/bin/php                                
 PHP configuration               :                                                    
 PHP OS                          :  Linux                                             
 Drush script                    :  /app/vendor/drush/drush/drush.php                 
 Drush version                   :  8.1.5                                             
 Drush temp directory            :  /tmp                                              
 Drush configuration             :                                                    
 Drush alias files               :                                                    
 Install profile                 :  standard                                 
 Drupal root                     :  /app/web                                          
 Drupal Settings File            :  sites/default/settings.php                        
 Site path                       :  sites/default                                     
 File directory path             :  sites/default/files                               
 Temporary file directory path   :  /tmp`

Same issue using drupal console unable to list --root=/app/web to resolve

**Comment by s3than** [comment]
Created a PR for checking if Drupal Console is installed globally or within the project.

**Comment by chriscalip** [comment]
Also currently getting this error. 
Steps to replicate:
a.) New vagrant box.
b.) Do steps in https://drupalconsole.com/

**Comment by s3than** [comment]
Just an update the autoload now works as expected. However the actual check if drupal is installed doesn't confirm installation and there appears to be some other autoloading problems around database functionality.

**Comment by s3than** [comment]
Ok so narrowed the other issues down it appears that --root is being ignored

**Comment by jmolivas** [comment]
@kentr did you installed by `composer global update` / `composer global update` or by using the `self-update` command ?

**Comment by jmolivas** [comment]
@chriscalip: I have seen issue when using DrupalVM maybe is also happening with other VMs

**Comment by kentr** [comment]
@jmolivas Yes, I'm using DrupalVM. I don't actually remember running an update. But if I did it, my guess is that it was with `self-update`.  DC doesn't appear to be installed with `composer global`.

DrupalVM installs with this [Ansible role](https://github.com/geerlingguy/ansible-role-drupal-console).  Do you see anything in the [installation sequence](https://github.com/geerlingguy/ansible-role-drupal-console/blob/master/tasks/main.yml) that would lead to this error?

**Comment by kentr** [comment]
I think DrupalVM is running `drupal init` as `root`.  There's no `.console` directory in the `vagrant` user home directory.

Even so, I get the same error when I login as `root`and run `drupal list` in the drupal web dir.

Like with s3than, adding the `--root` option doesn't change anything: `drupal --root=/var/www/drupalvm list`.

**Comment by jmolivas** [comment]
@kentr can you try:
```
drupal init --override --no-interaction
```

**Comment by kentr** [comment]
@jmolivas Thanks.

Does the file `.console/sites/drupalvm.yml` have any bearing on this problem?  The information in that file is incorrect.

**It contains:**

```
dev:
  root: /var/www/drupalvm/drupal
  host: 192.168.88.88
  user: vagrant
  password: vagrant
  console: /usr/local/bin/drupal
```

**I'd guess it should be something like this:**

```
dev:
  root: /var/www/drupalvm
  host: 192.168.88.88
  user: (what user is this?)
  password: (what user is this?)
  console: /usr/local/bin/drupal
```

**Comment by jmolivas** [comment]
@kentr  since running commands via `vagrant ssh` and not remote from host machine that config is not used.

**Comment by jmolivas** [comment]
@kentr did this helps https://github.com/hechoendrupal/DrupalConsole/issues/2785#issuecomment-252827321?

**Comment by kentr** [comment]
@jmolivas Running `drupal init --override --no-interaction` didn't correct the error.  I tried with both the `vagrant` user and `root` user.

**Comment by jmolivas** [comment]
if not can you please

```
cd  /var/www/drupalvm (the drupal site root)
drupal init (answer yes to Copy at current directory console/config.yml? (yes/no) [yes]:)
```

**Comment by kentr** [comment]
@jmolivas That didn't correct the error, unfortunately.

Here's the contents of the new `/var/www/drupalvm/console/config.yml`:

```yml
  environment: 'prod'
  language: 'en'
  editor: 'vim'
  temp: '/tmp'
  develop: 'false'
  command: 'about'
  checked: 'false'
  remote:
    user: 'root'
    port: '22'
    console: '/usr/local/bin/drupal'
    keys:
      public: '~/.ssh/id_rsa.pub'
      private: '~/.ssh/id_rsa'
      passphrase: '~/.ssh/passphrase.txt'
  composer:
    create-project:
      default:
        package: 'drupal-composer/drupal-project'
      drupal:
        package: 'drupal/drupal'
    repositories:
      default: 'https://packagist.drupal-composer.org'
      drupal: 'https://packages.drupal.org/8'
      packagist: 'https://packagist.org'
  disable:
    modules:
#      - module_name_one
#      - module_name_two
    commands:
      module:download: 'composer require drupal/project'
      module:update: 'composer update drupal/project'
      theme:download: 'composer require drupal/project'
      theme:update: 'composer update drupal/project'
    namespaces:
#      - generate
#      - create
  options:
    learning: true
#    target: drupalvm.dev
#    uri: miltisite.dev
    generate-inline: false
    generate-chain: false
##    yes: false
    composer: false
    root: '/var/www/drupalvm'
```
