### ISSUE TITLE
[print:message] Print command

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console#2861]
for chain commands execution and bash scripts, would be great if i could print messages, errors, infos from DrupalConsole.
i propose a `print` command:
- print:message
- print:error
- print:info
  that only prints a string (using DrupalStyle?) as argument

i can work on this if maintainers would consider it useful

**Comment by novia713** [comment]
closing because i can't find good usecases

**Comment by novia713** [comment]
i've just found an usecase, @jmolivas 
imagine, you're coding a chain file for DrupalConsole and you want to print a Welcome message,
(usecase for `print:message`)
even you need to ask the user if he wants to perform an optional action
(usecase for `ask`) 

i would do all this in drupal-core

**Comment by marcelovani** [comment]
Can't you use echo?
i.e.
```
commands:
# Display message
  - command: exec
    arguments:
      bin: 'echo "Message here"'
```
