### ISSUE TITLE
Cannot get to work remotely with Drupal VM instance.

### ISSUE THREAD

**Issue by kevinquillen** [hechoendrupal/drupal-console#3096]
### Problem/Motivation

I followed the docs for setting up Drupal Console with a remote vm. When I run site:debug, I see my local site listed, but I cannot run any commands.

```
drupal --target=d8.local list                                                                            [01/14/17  2:06AM]

Warning: file_get_contents(): Filename cannot be empty in /Users/kevinquillen/.composer/vendor/drupal/console/src/Helper/RemoteHelper.php on line 51
commands.site.debug.messages.error-connect
```

It apparently is complaining about a lack of `passphrase.txt` in my `.ssh` directory. What do I do?

**Comment by jmolivas** [comment]
@kevinquillen can you execute on your host `drupal init` and select you user home directory as destination. 

The remote section of your `~/.console/ocnfig.yml` file:
```
    remote:
        user: drupal
        port: '22'
```
You probably have the old format:
```
  remote:
    user: 'root'
    port: '22'
    console: '/usr/local/bin/drupal'
    keys:
      public: '~/.ssh/id_rsa.pub'
      private: '~/.ssh/id_rsa'
      passphrase: '~/.ssh/passphrase.txt'
```

**Comment by kevinquillen** [comment]
Okay, I made that change. My site file looks like this:

```
 local:
    root: /Users/kevinquillen/Servers/d8
    host: local.d8.com
```

My generating config.yml - now with your suggested change, looks like this:

```
application:
  environment: 'prod'
  language: en
  editor: vim
  temp: /tmp
  develop: 'false'
  command: about
  checked: 'false'
  remote:
    user: root
    port: 22
```

However, I still get this when running a command:

```
drupal --target=d8.local list                                                                         

Warning: file_get_contents(): Filename cannot be empty in /Users/kevinquillen/.composer/vendor/drupal/console/src/Helper/RemoteHelper.php on line 51
commands.site.debug.messages.error-connect
```

**Comment by jmolivas** [comment]
@kevinquillen which version of DrupalConsole version Launcher do you have installed?

**Comment by kevinquillen** [comment]
Drupal Console version 0.11.3

**Comment by jmolivas** [comment]
@kevinquillen that is pretty old. Can you update to RC-14?

Starting on RC releases DC should be install per site. (In your case this was done by DrupalVM).

If you like to use the remote features you need to install the global executable now named Launcher
```
curl https://drupalconsole.com/installer -L -o drupal.phar
mv drupal.phar /usr/local/bin/drupal
chmod +x /usr/local/bin/drupal
```

**Comment by kevinquillen** [comment]
Thats odd, I installed it with:

`composer global require drupal/console`

If I remove it with composer, and do

`composer global require drupal/console@stable`

Then I get version 0.2.6.

**Comment by kevinquillen** [comment]
Oh, okay, I was following the documentation. Let me try it that way.

**Comment by jmolivas** [comment]
@kevinquillen As mentioned, starting on RC releases DC should be install per site.

```
# Change directory to Drupal site
cd /path/to/drupal8.dev

# Download DrupalConsole
composer require drupal/console:~1.0 \
--prefer-dist \
--optimize-autoloader \
--sort-packages
```

The `composer global require` installation is discouraged to avoid conflict between dependencies.

You can still have a global executable by using the Launcher 
```
curl https://drupalconsole.com/installer -L -o drupal.phar
mv drupal.phar /usr/local/bin/drupal
chmod +x /usr/local/bin/drupal
```

**Comment by kevinquillen** [comment]
Alright, now RC-14 is installed locally to the project, and I did `drupal init`. Now my config.yml looks better, and I created a new site file based on the drupalvm.yml file.

Output of `site:debug`:

```
 [ERROR] SQLSTATE[HY000] [2002] No such file or directory                                                               

 -------------- ----------------- -------------------------- 
  Site           Host              Root                      
 -------------- ----------------- -------------------------- 
  d8.local       local.d8.com      /var/www/d8/docroot       
  drupalvm.dev   192.168.88.88     /var/www/drupalvm/drupal  
  sample.local   local             /var/www/drupal8.dev      
  sample.dev     140.211.10.62     /var/www/html/drupal      
  sample.prod    live.drupal.org   /var/www/html/docroot     
 -------------- ----------------- -------------------------- 
```

The path on the remote machine is correct.

The output of `drupal list` or `drupal --target=d8.local list` prints a list of basic commands, followed with:

`[WARNING] In order to list all of the available commands you should install drupal first.`

The VM is up and running.

**Comment by jmolivas** [comment]
@kevinquillen Can you copy/paste the result of executing `drupal site:debug drupalvm.dev` ?

**Comment by kevinquillen** [comment]
```
[ERROR] SQLSTATE[HY000] [2002] No such file or directory                                                               

user: vagrant
port: '22'
root: /var/www/drupalvm/drupal
host: 192.168.88.88
password: vagrant
remote: true
```

**Comment by jmolivas** [comment]
Not sure why are you getting this error:
> [ERROR] SQLSTATE[HY000] [2002] No such file or directory.

I am updating DrupalVM on my local system to the latest version ping you back once is updated.

**Comment by jmolivas** [comment]
I see two issues:

1) This is happening on the host machine, since you are executing this form the host.
> [ERROR] SQLSTATE[HY000] [2002] No such file or directory.

2) Is your site on the Vm installed? 
> [WARNING] In order to list all of the available commands you should install drupal first.

**Comment by kevinquillen** [comment]
Yes, the site is installed.

**Comment by jmolivas** [comment]
@kevinquillen Not sure what is wrong in your host machine. I just cloned DrupalVM and execute `vagrant up` 

This is the content of my site file:

```
> cat ~/.console/sites/drupalvm.yml

dev:
  root: /var/www/drupalvm/drupal
  host: 192.168.88.88
  user: vagrant
  password: vagrant
```

This is the output of the `site:debug` command
```
> drupal site:debug drupalvm.dev

user: vagrant
port: '22'
root: /var/www/drupalvm/drupal
host: 192.168.88.88
password: vagrant
remote: true
```

I can execute `drupal --target=drupalvm.dev site:status`
```
> drupal --target=drupalvm.dev site:status

 System Info
 Drupal                    8.2.5
 Access to update.php      Protected
 Configuration files       Protected
 Cron maintenance tasks    Last run 2 hours 38 minutes ago
 Database system           MySQL, MariaDB, Percona Server, or equivalent
 Database system version   5.7.16-0ubuntu0.16.04.1-log
 Database updates          Up to date
 Devel module enabled
 Drupal core update status Up to date
 Entity/field definitions  Up to date
 File system               Writable (public download method)
 GD library                2.2.3
 GD library PNG support    2.2.3
 Image toolkit             gd
 Node Access Permissions   Disabled
 PHP                       7.0.14-2+deb.sury.org~xenial+1 (more information)
 PHP extensions            Enabled
 PHP memory limit          192M
 PHP OPcode caching        Enabled
 Search index progress     100% (0 remaining)
 Trusted Host Settings     Not enabled
 Unicode library           PHP Mbstring Extension
 Update notifications      Enabled
 Upload progress           Not enabled
 Web server
 Hash salt                 fT8a--yNsHG_mnChqa0fVsnmZPGzf6nrwUUP0IErqGvf23Qhf4ittqghVVMmAjOjguIrfjKUkQ
 Drupal Console            1.0.0-rc14

 Database connection
 Driver              mysql
 Host                localhost
 Database connection drupal
 Port
 Username            drupal
 Connection          mysql//drupal:drupal@localhost/drupal

 Themes
 theme_default bartik
 theme_admin   seven

 Directories
 Site root directory      /var/www/drupalvm/drupal/web
 Site temporary directory /tmp
 Default theme directory  /core/themes/bartik
 Admin theme directory    /core/themes/seven
```

**Comment by kevinquillen** [comment]
Could it be because Acquia BLT has a different process for setting up DrupalVM than just cloning it straight to your project? Here is the config.yml that it generates for me. The only line I changed, I believe, is enabling xdebug.

```
# Update the hostname to the local development environment hostname
vagrant_hostname: local.d8.com
vagrant_machine_name: d8

# Use Ubuntu 14.04 LTS to more closely match Acquia Cloud environment.
vagrant_box: geerlingguy/ubuntu1404

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "BLTed 8"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/d8
    type: nfs

build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
build_composer: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/d8"
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"

drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

# This is required for front-end building tools.
nodejs_version: "4.x"
nodejs_npm_global_packages:
  - name: bower
  - name: gulp-cli
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
installed_extras:
  - adminer
  - drush
  - mailhog
  - nodejs
  #- selenium
  - xdebug

# Use PHP 5.6.
php_version: "5.6"

# XDebug configuration.
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
# Change this value to 1 in order to enable xdebug on the cli.
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"

post_provision_tasks_dir: "../../../acquia/blt/scripts/drupal-vm/post-provision.yml"
post_provision_scripts:
  - "../../../acquia/blt/scripts/drupal-vm/post-provision.sh"
```

**Comment by jmolivas** [comment]
How can I test this?

Copy/paste previous content to my `config.yml` ?

How do I rebuild it?

**Comment by kevinquillen** [comment]
A clean way to do it would be:

`composer create-project --no-interaction acquia/blt-project d8`

I edited the project.yml for BLT to use the standard profile instead of lightning, and changed the project name to 'd8'.

Then,

`blt vm`
`blt local:setup`

I started my project using the [BLT guide here](http://blt.readthedocs.io/en/stable/readme/creating-new-project/).

**Comment by jmolivas** [comment]
@kevinquillen can you please copy/paste your site file the one at `~/.console/sites/d8.yml` ?

**Comment by jmolivas** [comment]
@kevinquillen should this `blt local:setup` execute from host or via ssh into the VM?

**Comment by kevinquillen** [comment]
I've been doing the commands from the host machine.

**Comment by jmolivas** [comment]
@kevinquillen I did that, follow those instructions  and it works for me:

```
composer create-project --no-interaction acquia/blt-project d8
cd d8
vendor/bin/blt vm
vendor/bin/blt local:setup
```
I created my site file `~/.console/sites/d8.yml`
```
> cat ~/.console/sites/d8.yml

local:
  root: /var/www/d8
  host: 192.168.88.88
  user: vagrant
  password: vagrant
```
After that execute `drupal --target=d8.local site:status` with this result: 
```
> drupal --target=d8.local site:status

 System Info
 Drupal                   8.2.5
 Installation profile     Lightning (lightning-)
 Access to update.php     Protected
 Configuration files      Protected
 Cron maintenance tasks   Last run 50 minutes 26 seconds ago
 Database system          MySQL, MariaDB, Percona Server, or equivalent
 Database system version  5.5.53-0ubuntu0.14.04.1-log
 Database updates         Up to date
 Entity/field definitions Up to date
 File system              Writable (public download method)
 GD library               2.2.3
 Image toolkit            gd
 Node Access Permissions  Disabled
 PHP                      5.6.29-1+deb.sury.org~trusty+1 (more information)
 PHP extensions           Enabled
 PHP memory limit         192M
 PHP OPcode caching       Enabled
 Private files directory  Not fully protected
 Public files directory   Not fully protected
 Trusted Host Settings    Not enabled
 Unicode library          PHP Mbstring Extension
 Update notifications     Not enabled
 Upload progress          Not enabled
 Web server
 Hash salt                wuSZqXerO1aRtSqRVAi4IDGRg85FIAghI76mwtzmFMjlULTcHOklOHp

 Drupal Console           1.0.0-rc14

 Database connection
 Driver              mysql
 Host                localhost
 Database connection drupal
 Port                3306
 Username            drupal
 Connection          mysql//drupal:drupal@localhost:3306/drupal

 Themes
 theme_default bartik
 theme_admin   seven

 Directories
 Site root directory      /var/www/d8/docroot
 Site temporary directory /tmp
 Default theme directory  /core/themes/bartik
 Admin theme directory    /core/themes/seven
```

**Comment by kevinquillen** [comment]
Thats so weird... I can't tell what the difference is.

`../vendor/bin/drupal site:debug d8.local `

```
user: vagrant
port: '22'
root: /var/www/d8
host: 192.168.88.88
password: vagrant
remote: true
```

```
local:
  root: /var/www/d8
  host: 192.168.88.88
  user: vagrant
  password: vagrant
```
