### ISSUE TITLE
[chain] - [multisite:new] [site:install] - Executing chain fails

### ISSUE THREAD

**Issue by brandonratz** [hechoendrupal/drupal-console#3197]
**Version:** Drupal Console (1.0.0-rc16)

# Problem
Using command: 'multisite:new' followed by 'site:install' via chain command fails.

# Expected behavior
1. Creates multisite directory
2. Installs site via multisite uri

# Actual Behavior

1. Creates multisite directory
2. ERROR: Invalid multisite error

## Console Output

```
 // multisite:new

[OK] The new multisite structure was successfully created at "sites/test.example.com" and is ready for installation.

 // site:install

[ERROR] Invalid multisite, please create multisite using command drupal multisite:new test.example.com
         --site-uri=test.example.com`
```

## Chain file example

```
commands:
  - command: 'multisite:new'
    options:
        learning: true
        uri: 'http://test.example.com'
    arguments:
        directory: 'test.example.com'
        uri: 'http://test.example.com'
  - command: 'site:install'
    options:
        langcode: en
        db-type: mysql
        db-host: localhost
        db-name: test_example_dev
        db-user: root
        db-pass: root
        db-port: '3306'
        site-name: 'Example Website'
        site-mail: admin@example.org
        account-name: admin
        account-mail: admin@example.org
        account-pass: password
        learning: true
        uri: 'http://test.example.com'
    arguments:
        profile: lightning
```
