### ISSUE TITLE
The site:new command does not work as per documentation.

### ISSUE THREAD

**Issue by petiar** [hechoendrupal/drupal-console#3226]
### Problem/Motivation
I would like to install Drupal the most easiest way. 

**Details to include:**
The documentation states:

`drupal site:new [arguments] [options]`, where arguments are directory and Drupal version.

I typed:

`drupal site:new . 8.2`

and got error saying:

`Too many arguments, expected arguments "command".`

### How to reproduce

Try to install Drupal using console. I dare you.

**Details to include:**

After I tried the site:status command I got this error:
`Fatal error: Call to undefined method Drupal\Console\Core\Utils\ConfigurationManager::loadExtendConfiguration() in /Users/petiar/Sites/medziriadky/vendor/drupal/console-core/src/Application.php on line 284`

### Solution
Either do it properly or lets do things the easiest way. Forget composer and console install and all that useless cool jibber jabber. Downloading Drupal from Drupal.org and install it via instal.php takes less time and, more importantly, it actually works.

**Details to include:**

**Comment by jmolivas** [comment]
We are talking about discarding site:new, module:download, theme:download and promote to use composer instead.

**Comment by carsonblack** [comment]
There is also this issue in the drupal-console-book repo: https://github.com/hechoendrupal/drupal-console-book/issues/261
@jmolivas I think I would tend to agree with promoting the use of Composer for this task as well since in D8 it's now a valid (and probably the best) option.  I'm guessing that there was already some discussion on this anyway which is why the command was removed. But by the time people are finding DrupalConsole they've probably already covered installation. Then again, if you're a person who needs to be able to quickly spin up new stuff on a regular basis site:new could be handy. But if you're one of those people, you probably already have some way of doing that with another tool. I do know people using md though.

**Comment by jmolivas** [comment]
The `site:new` command is back now.

**Comment by jmolivas** [comment]
You can use it like:
```
site:new
site:new --directory=/path/to/drupal-project/
site:new --repository=acquia/lightning-project --directory=/path/to/drupal-project/
```

make sure you run `drupal init` to copy configuration files

**Comment by jmolivas** [comment]
As mentioned by @carsonblack we are promoting the usage of composer 

This command is a chain command definition is at this file:
https://github.com/hechoendrupal/drupal-console-core/blob/master/config/dist/chain/site-new.yml

This file is copied when `drupal init` is executed:

This is the file content:
```
# How to use
# site:new --directory=/path/to/drupal-project/
# site:new --repository=acquia/lightning-project --directory=/path/to/drupal-project/
command:
  name: site:new
  description: 'Download a new Drupal project'
vars:
  repository:
    - drupal-composer/drupal-project:8.x-dev
    - acquia/lightning-project
    - acquia/reservoir-project
commands:
  # Create Drupal project using Composer
  - command: exec
    arguments:
      bin: composer create-project %{{repository}} %{{directory}} --prefer-dist --no-progress --no-interaction
```
