### ISSUE TITLE
[console] Add option for maintenance mode in certain commands

### ISSUE THREAD

**Issue by littlethoughts** [hechoendrupal/drupal-console#3313]
### Problem/Motivation

It would be nice to have an option whether the site should be put into maintenance mode, like --maintenance-mode for example.

More control over the command and a faster execution should be the outcome

**Comment by jmolivas** [comment]
@littlethoughts can you elaborate more on this feature request?

**Comment by LOBsTerr** [comment]
PR for DC: https://github.com/hechoendrupal/drupal-console/pull/3811
PR for DC Core:  https://github.com/hechoendrupal/drupal-console-core/pull/326

I have create a new maintenance listener, which checks maintenance property on the command and enable/ disable maintenance mode.
Currently, I enabled this functionality only for DB restore command. 
Please, let me know for which command we need this functionality.

**Comment by littlethoughts** [comment]
Cool, how could I test it?

I have a custom command where it would be useful, which is assembling config files. I could also achieve this functionality by writing a chain command I think. If that is much simpler than integrating your solution maybe that's enough.

From the top of my head, these would also be candidates, because they could be run in a production environment and take some time / need to preserve a state:

- database:dump
- cache:rebuild
- config:import
- queue:run

**Comment by jmolivas** [comment]
@littlethoughts I have not tested this feature. But what we commonly used chain commands is kinda like this. Add a new chain file at `console/chain/build.yml`
Containing this:
```
command:
  name: build
  description: 'Build site'
commands:
  # Import configuration
  - command: config:import
  # Rebuild caches.
  - command: cache:rebuild
    arguments:
        cache: all
```
Then use it as `drupal build`
