### ISSUE TITLE
Drupal Console cache?.. does it share? It causes weird effect for several instance of Drupal8 installation

### ISSUE THREAD

**Issue by vorapoap** [hechoendrupal/drupal-console#3328]
### Drupal Console Cache of many drupal installation for single linux user

[ *console* ] Several drupal installation under same user causing weird effect?

### Problem/Motivation
I have a single 'dev' user for many developers.
but each developers have his/her instance of Drupal8 installation.
I believe that rebuilding cache of one installation affects others.
For example, a smaller set of custom Drupal console commands on just the staging instance appears on  other instances as well (while the under-development commands disappears).. this is fixed by drupal cr all.

**Details to include:**
- Drupal Version: My staging is  8.3.2, my development is 8.3.1
- Drupal Console Version: 1.0.0-rc19
- Console Launcher version: 1.0.0-rc19

### Solution
`drupal cr all
in each instance directory fix the problem

**Comment by jmolivas** [comment]
@vorapoap  Is the site re-installer on each instance ? or the DB imported ?

**Comment by vorapoap** [comment]
DB import.. if you are asking about site-id. They are using the same.

**Comment by jmolivas** [comment]
@vorapoap Yes that was my question about the site-uuid number.

DrupalConsole generates a cache file for commands, you can try including this cache on your repository by adding a `console/config.yml` to your repo and committing that file.

Example of the contents for the file.
```
application:
  environment: 'prod'
  language: 'en'
  editor: 'vim'
  temp: '/tmp'
  cache:
    directory: 'console/cache/'
  develop: 'false'
  command: 'about'
  checked: 'false'
  clear: 'false'
```

You can generate that file by executing `drupal init` and selecting the path of your repo.

Also next DrupalConsole release will include a change on the composer plugin to clear that cache by removing that file when a new package is installed/updated by executing `composer install` or `composer update`.
