### ISSUE TITLE
Environment variables broken > rc-21 

### ISSUE THREAD

**Issue by prineshaz** [hechoendrupal/drupal-console#3381]
### [console] Environment variables in chain file not working

### Problem
Chaining a file with environment variables (via custom install yml file) may be broken in version 1.0.0-rc22 and 1.0.0-rc23.  We have a jenkins job which pulls in latest drupal/console & installs core drupal 8 via my custom install yml file. This implements the env variables approach defined [here](https://github.com/hechoendrupal/drupal-console/issues/2055).  It broke on Tuesday 27th June, i had to revert & fix the version to 1.0.0-rc21 to get it to install via env variables again.

**My Steps to reproduce:**
1. Export env variables
```
export DATABASE_USER=root
export DATABASE_PASSWORD=root
export DATABASE_NAME=drupal_8
export DATABASE_PORT=3306
export DATABASE_HOST=localhost
```

2. Run install Using this custom site-install-new.yml file with code below:

```
commands:
# Install Drupal
  - command: site:install
    options:
      langcode: en
      db-type: mysql
      db-host: '${{DATABASE_HOST}}'
      db-name: '${{DATABASE_NAME}}'
      db-user: '${{DATABASE_USER}}'
      db-pass: '${{DATABASE_PASSWORD}}'
      db-port: '${{DATABASE_PORT}}'
      site-name: 'Drupal 8'
      site-mail: admin@example.org # default email
      account-name: root # default account
      account-mail: admin@example.org # default email
      account-pass: root # default pass
    arguments:
      profile: standard
```

3. Execute 

`./vendor/bin/drupal chain --file=../console/chain/site-install-new.yml`

I get the following error:

```
[ERROR] commands.chain.messages.missing-environment-placeholders-default                                               

 commands.chain.messages.set-environment-placeholders-custom

 export 0=0_VALUE                                                                                                       
                                                                                                                        
 export 1=1_VALUE                                                                                                       
                                                                                                                        
 export 2=2_VALUE                                                                                                       
                                                                                                                        
 export 3=3_VALUE                                                                                                       
                                                                                                                        
 export 4=4_VALUE
```

Rolling back to 1.0.0-rc21 fixed this.

**Details to include:**
- Drupal 8.3
- Console version: 1.0.0-rc23
- Console Launcher version : Drupal Console version 1.0.0-rc23
