### ISSUE TITLE
'drupal upex': Too few arguments to function system_update_8400()

### ISSUE THREAD

**Issue by simesy** [hechoendrupal/drupal-console#3505]
### Issue title

The issue title should comply with the following structure:

`upex` fails to system_update_8400() 

### Problem/Motivation
When I run `drupal upex` on Drupal 8.4 Beta 1, I expect it to run my update.

### How to reproduce
Have a site on Drupal 8.3 and update to 8.4 and with `drupal upex` using Console version 1.0.1.

**Details to include:**
```
vagrant@lilengine:/var/www/drupalvm/web$ ../vendor/bin/drupal upex
 Executing update function "8400" of module "system"
 Move revision metadata fields to the revision table.

ArgumentCountError: Too few arguments to function system_update_8400(), 0 passed and exactly 1 expected in /var/www/drupalvm/web/core/modules/system/system.install on line 1847 #0 [internal function]: system_update_8400()
#1 /var/www/drupalvm/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('system_update_8...', Array)
#2 /var/www/drupalvm/vendor/drupal/console/src/Command/Update/ExecuteCommand.php(244): Drupal\Core\Extension\ModuleHandler->invoke('system', 'update_8400')
#3 /var/www/drupalvm/vendor/drupal/console/src/Command/Update/ExecuteCommand.php(140): Drupal\Console\Command\Update\ExecuteCommand->runUpdates(Object(Drupal\Console\Core\Style\DrupalStyle), Array)
#4 /var/www/drupalvm/vendor/symfony/console/Command/Command.php(264): Drupal\Console\Command\Update\ExecuteCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/drupalvm/vendor/symfony/console/Application.php(859): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/drupalvm/vendor/symfony/console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Update\ExecuteCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/drupalvm/vendor/drupal/console-core/src/Application.php(163): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/drupalvm/vendor/drupal/console/src/Application.php(71): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/drupalvm/vendor/symfony/console/Application.php(125): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/drupalvm/vendor/drupal/console/bin/drupal.php(88): Symfony\Component\Console\Application->run()
#11 /var/www/drupalvm/vendor/drupal/console/bin/drupal(4): require('/var/www/drupal...')
#12 {main}
ArgumentCountError: Too few arguments to function system_update_8400(), 0 passed and exactly 1 expected in system_update_8400() (line 1847 of /var/www/drupalvm/web/core/modules/system/system.install).

```

**Comment by simesy** [comment]
Hi, I have applied this patch referenced above, confirmed that it is applied in the source code, cleared caches, but the problem is the same.

**Comment by jmolivas** [comment]
@simesy I was able to replicate this issue by creating a chain file `~/.console/chain/3505.yml`

File contents:
```
# How to use
command:
  name: test:3305
  description: 'Test issue 3305'
commands:
  - command: exec
    arguments:
      bin: drupal site:new --repository=drupal-composer/drupal-project:8.x-dev --directory=%{{directory}}
  - command: exec
    arguments:
      bin: composer remove drush/drush --working-dir=%{{directory}}
  - command: exec
    arguments:
      bin: drupal site:install standard --db-user=root --db-pass=root --force --no-interaction --root=%{{directory}}
  - command: exec
    arguments:
      bin:
  - command: exec
    arguments:
      bin: composer require drupal/core:8.4.0-beta1 --no-update --working-dir=%{{directory}}
  - command: exec
    arguments:
      bin: composer update --working-dir=%{{directory}}
  - command: exec
    arguments:
      bin: drupal upex --root=%{{directory}}

```
And executing like this
```
drupal test:3305 --directory=/Users/jmolivas/develop/drupal/sites/drupal8.dev
```

I got the same error you mentioned 
```
Executing update function "8400" of module "system"
 Move revision metadata fields to the revision table.

ArgumentCountError: Too few arguments to function system_update_8400(), 0 
passed and exactly 1 expected in system_update_8400() (line 1847 of /Users/jmolivas/develop/drupal/sites/drupal8.dev/web/core/modules/system/system.install).
```

**Comment by jmolivas** [comment]
@simesy I was able to replicate this issue by creating a chain file `~/.console/chain/3505.yml`

File contents:
```
# How to use
command:
  name: test:3305
  description: 'Test issue 3305'
commands:
  - command: exec
    arguments:
      bin: drupal site:new --repository=drupal-composer/drupal-project:8.x-dev --directory=%{{directory}}
  - command: exec
    arguments:
      bin: composer remove drush/drush --working-dir=%{{directory}}
  - command: exec
    arguments:
      bin: drupal site:install standard --db-user=root --db-pass=root --force --no-interaction --root=%{{directory}}
  - command: exec
    arguments:
      bin:
  - command: exec
    arguments:
      bin: composer require drupal/core:8.4.0-beta1 --no-update --working-dir=%{{directory}}
  - command: exec
    arguments:
      bin: composer update --working-dir=%{{directory}}
  - command: exec
    arguments:
      bin: drupal upex --root=%{{directory}}

```
And executing like this
```
drupal test:3305 --directory=/Users/jmolivas/develop/drupal/sites/drupal8.dev
```

I got the same error you mentioned 
```
Executing update function "8400" of module "system"
 Move revision metadata fields to the revision table.

ArgumentCountError: Too few arguments to function system_update_8400(), 0 
passed and exactly 1 expected in system_update_8400() (line 1847 of 
/Users/jmolivas/develop/drupal/sites/drupal8.dev/web/core/modules/system/system.install).
```
