### ISSUE TITLE
Setting alias to run drupal console commands on remote vagrant machine

### ISSUE THREAD

**Issue by adriadrop** [hechoendrupal/drupal-console#3523]
Having problem on Mac OSx (sierra).

So I read this issue about how now there is no composer global require anymore and you need to install launcher and a DC per site https://github.com/hechoendrupal/drupal-console/issues/3250#issuecomment-291912031

I also read how to put ALIAS for remote access https://hechoendrupal.gitbooks.io/drupal-console/content/en/alias/using-site-alias.html 
So this would be output of my alias 

~/Drupal/my-project/vendor/bin : tail ~/.console/sites/my-project.yml

```
dev:
  root: /var/www/my-project/docroot
  host: 192.168.199.62
  user: vagrant
  extra-options: '-o PasswordAuthentication=no -i ~/.vagrant.d/insecure_private_key'
  type: ssh
```

Then when I try to run this drupal --target=my-project.dev site:status I get

> 
> Warning: array_merge(): Argument #1 is not an array in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 156
> [ERROR] Command "site:status", is not a valid command name.  

I am assuming name of the target is the name of alias file (my-project) and then adding .dev to it. But seems to me like its not using it, as I would expect some delay trying to connect to VM, this goes in a second and throws this warning and error.
