### ISSUE TITLE
Allow config:override command to work with arrays

### ISSUE THREAD

**Issue by marcelovani** [hechoendrupal/drupal-console#3540]
### Allow config:override command to work with arrays
[config:override] Add support for this command to receive an array of configs as well as single config

### Problem/Motivation
I would like to create chain commands that set a bunch of configs at once

### How to reproduce
If I want to create a chain to set a bunch of values, it would look like this
```
commands:
  # system.performance
  - command: config:override
    arguments:
      name: system.performance
      key: cache.page.use_internal
      value: false
  - command: config:override
    arguments:
      name: system.performance
      key: css.preprocess
      value: false
```

I want to be able to do this like this
```
commands:
  # system.performance
  - command: config:override
    arguments:
      name: system.performance
      values:
        - cache.page.use_internal: false
        - css.preprocess: false
```

### Solution
We could add the ability to receive arrays to https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Config/OverrideCommand.php

**Comment by LOBsTerr** [comment]
It looks like we require this feature more and more. I will implement it soon.
The only my concern here, we should warn the users, which still use the old syntax in the chain files.
So, I have few ideas
1) Create an additional command **config:override:multiple** and inside use **config:override**. Then mark it as deprecated.
2) Support both options and handle it differently. What I personally don't like>

@jmolivas What do you think?

**Comment by jmolivas** [comment]
I like the idea @marcelovani & @LOBsTerr 

Adding a new command `config:override:multiple` seems like more code to maintain and can introduce some confusion.

Keep the same command `config:override` and support both sounds cumbersome but my suggestion is not replacing the old argument is to:

Add a new option as array to support multiple key/value  
```
  ->addOption(
    'key-value',
    null,
    InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY,
    $this->trans('commands.config.override.options.key-value')
  )
```

Use it as:
```
commands:
  # system.performance
  - command: config:override
    arguments:
      name: system.performance
    options:
      key-value:
        - cache.page.use_internal: false
        - css.preprocess: false
```

**Comment by marcelovani** [comment]
Yes, I actually have played with that the other day, I can post my code here this evening.
The only issue is that the existing argument 'value' will have to be changed to optional too.
We can always add a validation on execute() to make sure that at least one of the two arguments is present.

**Comment by jmolivas** [comment]
Exactly, both have to be defined as optional and the validation must be introduced.

**Comment by marcelovani** [comment]
I like this. One thing to keep in mind is that config can have multiple levels of nesting.
Which we would pass via key-value, like domain.config.alias.config_token.tokens
I think we can use the built in code from config manager to map these keys

**Comment by harold20** [comment]
This is already implemented.

You can defined the chain for multiple values like

```
commands:
  - command: 'config:override'
    arguments:
        name: views.view.who_s_new 
    options:
        key:
            - uuid
            - description
        value:
            - 123r4-1234r5-123f6
            - 'new description'
        uri: 'http://default'
```
