### ISSUE TITLE
Use chains to replace site:mode command

### ISSUE THREAD

**Issue by marcelovani** [hechoendrupal/drupal-console#3541]
### Issue title

[site:mode] Use chains to replace site:mode command

### Problem/Motivation
Since chains are getting more powerful, I figured we could replace the code found in https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Site/ModeCommand.php with a chain

**Details to include:**
We can simply have less code to maintain and add more flexibility to users

### Solution
- We should be able to delete most of the code found in
https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Site/ModeCommand.php and the actual site.mode.yml
- We still need to port the functionality of doing the **services** bit found in site.mode.yml
- We can move the ModeCommand into a folder called Legacy, for people running site:mode command we would tell them to use the new chains
- This issue requires #3540 

This is how the site:mode:dev chain would look
```
command:
  name: site:mode:dev
  description: 'Switch system performance configuration'
commands:
  # system.performance
  - command: config:override
    arguments:
      name: system.performance
        - cache.page.use_internal: false
        - css.preprocess: false
        - css.gzip: false
        - js.preprocess: false
        - js.gzip: false
        - response.gzip: false
  # views.settings
  - command: config:override
    arguments:
      name: views.settings
        - ui.show.sql_query.enabled: true
        - ui.show.performance_statistics: true
  # system.logging
  - command: config:override
    arguments:
      name: system.logging
        - error_level: all
```

The prod chain would be the inverse of the chain above

**Comment by marcelovani** [comment]
Another proof of concept: Use twig + a new command to override services.

```
# How to use
# site:mode --mode="dev"
command:
  name: site:mode
  description: 'Changes the site mode'
vars:
  mode:
    - dev
    - prod
commands:
  # System Performance
  {% set keys = ['cache.page.use_internal', 'css.preprocess', 'css.gzip', 'js.preprocess', 'js.gzip', 'response.gzip'] %}
  {% for key in keys %}
  - command: config:override
    arguments:
      name: system.performance
      key: {{ key }}
      value: {% if mode == "dev" %} false {% else %} true {% endif %}
  {% endfor %}

  # Views settings
  {% set keys = ['ui.show.sql_query.enabled', 'ui.show.performance_statistics'] %}
  {% for key in keys %}
  - command: config:override
    arguments:
      name: views.settings
      key: {{ key }}
      value: {% if mode == "dev" %} false {% else %} true {% endif %}
  {% endfor %}

  # System Logging
  - command: config:override
    arguments:
      name: system.logging
      key: error_level
      value: {% if mode == "dev" %} all {% else %} none {% endif %}

  # Services http.response.debug_cacheability_headers
  - command: service:override
    arguments:
      name: http.response.debug_cacheability_headers
      key: error_level
      value: {% if mode == "dev" %} true {% else %} false {% endif %}

  # Services Twig config
  {% set keys = ['debug', 'auto_reload', 'cache'] %}
  {% for key in keys %}
  - command: service:override
    arguments:
      name: twig.config
      key: {{ key }}
      value: {% if mode == "dev" %} true {% else %} false {% endif %}
  {% endfor %}
```

The if/else is not working, I think I am using an invalid syntax
