### ISSUE TITLE
Build:local: Unable to run site:install over existing installation

### ISSUE THREAD

**Issue by oukjweather** [hechoendrupal/drupal-console#3571]
### Build:local Unable to run site:install

When running the following yaml file called build-local after the first install:
```
command:
  name: build:local
  description: 'Build local development site'
commands:
  # install site
  - command: site:install
    options:
      langcode: en
      db-type: 'mysql'
      db-host: 'mariadb'
      db-name: 'drupal'
      db-user: 'drupal'
      db-pass: 'drupalpass'
      db-port: '3306'
      site-name: 'Drupal 8 site'
      site-mail: admin@example.org # default email
      account-name: admin # default account
      account-mail: admin@example.org # default email
      account-pass: admin # default pass   
      force: true
    arguments:
      profile: standard
```
get back error:

![screen shot 2017-11-02 at 2 50 53 pm](https://user-images.githubusercontent.com/8658773/32347096-94fc68a2-bfdd-11e7-9503-19879530a127.png)

### How to reproduce
- Start with a fresh install from docker4drupal. https://github.com/wodby/docker4drupal using the wodby/drupal-php:7.1-3.0.0 image.

- Start a new drupal-composer/drupal-project

- Insert the build yaml file.
- Setup the docker alias. 

-  Run the command:
```
drupal build:local --target=docker.dev
```

Now run it again over the first successful install.

Versions:
```
drupal-composer/drupal-scaffold: 2.3.0
drupal/console: 1.0.2
drupal/console-core: 1.0.2
drupal/console-dotenv: 0.3.0
drupal/console-en: 1.0.2
drupal/console-extend-plugin: 0.9.2
drupal/core: 8.4.1
drush/drush: 8.1.15
```
