### ISSUE TITLE
site:install sitename is not being picked up 

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3613]
### Issue title

The issue title should comply with the following structure:

[ *site:install* ] sitename is not being picked up

### Problem/Motivation
When you fill in a sitename in the following prompt, it will not be used and `Drupal` will always become the sitename:
```
Provide your Drupal site name
```

### How to reproduce
Run site:install interactively and fill in a site name, note that the site name has not been picked up and will always be `Drupal`.

**Comment by heilop** [comment]
Hi @nvaken, I try to replicate this issue using the latest version (1.3.1) and it works fine. I tested by executing the following:
* Interactive mode.
* Inline mode.
```
drupal site:install  standard --langcode="en" --db-type="sqlite" \
--db-file="sites/default/files/.ht.sqlite" --site-name="My D8 site!" \
--site-mail="admin@example.com" --account-name="admin" \
--account-mail="admin@example.com" --account-pass="1234" \
--uri="http://default" --no-interaction
```
* Chain command:
```
command:
  name: site:install:test
  description: 'Build test site'
commands:
  - command: 'site:install'
    options:
        langcode: en
        db-type: sqlite
        db-file: sites/default/files/.ht.sqlite
        site-name: 'My D8 site!'
        site-mail: admin@example.com
        account-name: admin
        account-mail: admin@example.com
        account-pass: '1234'
        uri: 'http://default'
    arguments:
        profile: standard
```
