### ISSUE TITLE
Regular (non-command) extended services are not to be included in DC service files

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3783]
When using the following `console.services.yml`, `my_lib_console.configuration_helpers` is not being picked up by DC. As discussed with @jmolivas through Gitter, DC probably only caches _command_ services. For more background info, see [Gitter discussion](https://gitter.im/hechoendrupal/DrupalConsole?at=5a829ca9ce68c3bc747ce1c5).

```
services:
  console.my_lib_console.env.pull_config:
    class: \Drupal\Console\MyLibConsole\Command\Env\PullConfigCommand
    tags:
      - { name: drupal.command, bootstrap: uninstall}
  my_lib_console.configuration_helpers:
    class: Drupal\Console\MyLibConsole\Utils\ConfigurationHelpers
    arguments: ['@console.configuration_manager']
```
