### ISSUE TITLE
[drupal chain] [ERROR] You must provide a valid file path and name

### ISSUE THREAD

**Issue by SuperNami** [hechoendrupal/drupal-console#3990]
### Unable to get drupal chain command to work

[ *ISSUE-GROUP* ] `drupal chain`

### Problem/Motivation

I have tried all possible combinations (as far as I know) to try to get the `drupal chain` command to work but it always fails with the same error:

`[ERROR] You must provide a valid file path and name`

### How to reproduce

**Versions**
- Drupal 8.6.3
- Console 1.8.0
- Drupal Console Launcher 1.8.0

**Steps to reproduce**
Any of the following command combinations:

````
drupal chain site:install:env --file site-install-env.yml
drupal chain site:install:env --file "site-install-env.yml"\
drupal chain site:install:env --file relative/path/site-install-env.yml
drupal chain site:install:env --file /absolute/path/site-install-env.yml
drupal chain site:install:env --file /absolute/path/chain/console/site-install-env.yml
drupal chain site:install:env --file=site-install-env.yml
drupal chain site:install:env --file="site-install-env.yml"
drupal chain site:install:env --file=/direct/path/to/site-install-env.yml
drupal chain --command=site:install:env --file=site-install-env.yml
drupal chain --commands=site:install:env --file=site-install-env.yml
etc
````

site-install-env.yml file
````
command:
  name: site:install:env
  description: 'Install site using environment placeholders'
commands:
  - command: site:install
    options:
      langcode: en
      db-type: '{{ env("DB_TYPE") }}'
      db-host: '{{ env("DB_HOST") }}'
      db-name: '{{ env("DB_NAME") }}'
      db-user: '{{ env("DB_USER") }}'
      db-pass: '{{ env("DB_PASSWORD") }}'
      db-port: '{{ env("DB_PORT") }}'
      site-name: 'Drupal 8 site'
      site-mail: '{{ env("SITE_EMAIL") }}'
      account-name: '{{ env("DRUPAL_LOGIN_USERNAME") }}'
      account-mail: '{{ env("SITE_EMAIL") }}'
      account-pass: '{{ env("DRUPAL_LOGIN_PASSWORD") }}'
    arguments:
      profile: 'standard'
````

**Gitlab CI output (all above commands fail like this)**
![2018-11-29_15-02](https://user-images.githubusercontent.com/24568457/49226763-c7360000-f3e7-11e8-92e3-093c8de88569.png)

### Solution

No suggestions so far.
