### ISSUE TITLE
[Console] Cannot connect to Pantheon remote site and run Drupal Console commands

### ISSUE THREAD

**Issue by ryanprager** [hechoendrupal/drupal-console#3997]
### Problem/Motivation
I'm unable to connect to a remote Pantheon site to run Drupal Console commands.

### How to reproduce
Locally, I've setup a file called ssh.yml in console/sites that has the following parameters (certain identifiable items have been replaced be #####:

```
dev:
  root: /srv/bindings/#####/code/web
  host: appserver.dev.#####.drush.in
  user: dev.#####
  type: ssh
  port: 2222
  extra-options: '-o "AddressFamily inet"'
```

When I run this command:
`drupal @ssh.dev`

I get this output:
`PTY allocation request failed on channel 0`

I can run Drush commands against this and other Pantheon sites without a problem.

Is my ssh.yml file setup correctly for Pantheon or is there something else going on?

**Details:**
- Drupal version: 8.6.5
- Console version: 1.8.0
- Console Launcher version: 1,8.0
- Local OS: Windows 10
- Running commands with Git Bash for Windows

Any help is greatly appreciated. Thanks!
