### ISSUE TITLE
[console] 500 error on console installer page.

### ISSUE THREAD

**Issue by vivekpan27** [hechoendrupal/drupal-console#4262]
### Problem/Motivation
TASK [geerlingguy.drupal-console : Install Drupal Console.] ********************
fatal: [alshaya]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drupal", "elapsed": 1, "msg": "Request failed", "response": "HTTP Error 500: Internal Server Error", "status_code": 500, "url": "https://drupalconsole.com/installer"}

**Details to include:**
- Got this while trying to provision for DrupalVM. https://drupalconsole.com/installer is not opening

### How to reproduce
Visit https://drupalconsole.com/installer.
OR 
try to provision for DrupalVM.

**Comment by jcaillot** [comment]
As a **temporary** workaround, I could obtain a copy of the "drupal.backup" executable from a team mate that already had its VM provisionned and I changed this task in Ansible :

```
- name: Install Drupal Console.
  get_url:
    url: https://drupalconsole.com/installer
    dest: "{{ drupal_console_path }}"
```
    
for:

```
- name: Copy Drupal Console (temporary workaround).
  copy:
    src: /path/to/local/copy/of/drupal.backup
    # drupal_console_path in VM is /usr/local/bin/drupal
    dest: "{{ drupal_console_path }}"
```
    
I also disabled the "drupal console" self-update task a few lines below. 
I was then able to run `vagrant up --provision` without issue.

**Comment by jcaillot** [comment]
As a (very ugly) temporary workaround, I could obtain a copy of the "drupal" executable from a team mate that already had its VM provisionned and I changed this task in ansible :

```
- name: Install Drupal Console.
  get_url:
    url: https://drupalconsole.com/installer
    dest: "{{ drupal_console_path }}"
```
    
for:

```
- name: Copy Drupal Console (temporary workaround).
  copy:
    src: /path/to/local/copy/of/drupal
    # drupal_console_path in VM is /usr/local/bin/drupal
    dest: "{{ drupal_console_path }}"
```
    
I also disabled the "drupal console" self-update task a few lines below. 
I was then able to run `vagrant up --provision` without issue.

**Comment by zxcs001** [comment]
@jcaillot Do you have any idea where we can download a provision or legacy version?

**Comment by zxcs001** [comment]
@jcaillot Do you have any idea where we can download a legacy version?

**Comment by elizoller** [comment]
I am also receiving a 500 Internal Server Error from https://drupalconsole.com/installer

**Comment by vivekpan27** [comment]
Yes, the drupal console team has to solve that issue.
Till then I guess we can use the method that @jcaillot has shown or we can remove drupalconsole from our ansible script(if we are using ansible) for the time if we do not explicitly require it. We can later add it back and re-provision the VM to get it into our system.

**Comment by justrussian** [comment]
Where to find this executable?

**Comment by vivekpan27** [comment]
You can ask someone to provide you with the executable.
Or you can use composer:
`composer require drupal/console`
Then you can run drupalconsole using: `vendor/bin/drupal`

**Comment by unknownterritory** [comment]
Considering that the DC team is planning to remove this installer in future versions, creating a .bashrc alias or adding vendor/bin to path might be more future friendly workarounds.

**Comment by unknownterritory** [comment]
To fully install Drupal Console and add `/vendor/bin` to the `$PATH`, on Ubuntu, using Ansible:

```yaml
  tasks:
    - name: Require Drupal Console.
      composer:
        command: require
        arguments: drupal/console:~1.0
        working_dir: "/var/www/{{ project }}"
        prefer_dist: yes
        optimize_autoloader: yes
      become: false
      environment:
        COMPOSER_PROCESS_TIMEOUT: 1200
        COMPOSER_MEMORY_LIMIT: '-1'
    - name: Add project's /vendor/bin to $PATH
      lineinfile:
        path: ~/.profile
        line: 'PATH="$PATH:/var/www/{{ project }}/vendor/bin"'
        state: present
      become: false
```
